server:
  port: 8090

commentsrv:
  userName: ${TECH_USER:texuser}
  password: ${TECH_PAROL:123456}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    eviction-interval-timer-in-ms: 15000
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name:
    username:
    password:
    initialization-mode: always
  application:
    name: commentService
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
  liquibase:
    changeLog: classpath:/db/changelog/changelog.xml
  messages:
    basename: i18n/messages
  mvc:
    hiddenmethod:
      filter:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always

h2:
  console:
    enabled: true
settings:
  local: ru-RU




