spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
  liquibase:
    changeLog: classpath:/db/changelog/changelog.xml
  messages:
    basename: i18n/messages
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always

logging:
  file:
    path: ./logs
h2:
  console:
    enabled: true
settings:
  local: ru-RU

commentServer:
  host: "http://localhost:8090"


