spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name:
    username:
    password:
    initialization-mode: always
  application:
    name: booklib
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
  liquibase:
    changeLog: classpath:/db/changelog/changelog.xml
  messages:
    basename: i18n/messages
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8088
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always

h2:
  console:
    enabled: true
settings:
  local: ru-RU

commentServer:
  host: ${COMMENT_SERVICE_NAME:"http://localhost"}
  port: ${COMMENT_SERVICE_PORT:"8090"}
  eurekaserver: ${EUREKA_SERVER:localhost}

eureka:
  prefer-ip-address: true
  instance-id: ${spring.cloud.client.ip-address}:${server.port}
  hostname: ${spring.cloud.client.ip-address}
  client:
    service-url:
      defaultZone: http://${commentServer.eurekaserver}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    eviction-interval-timer-in-ms: 15000




